### ISSUE TITLE
Review, "printer errors"

### ISSUE THREAD

**Issue by vr8hub** [jlund/jack-black_you-cant-win#3]
We keep our changes to the text to a bare minimum. This obviously includes modernizations to spelling (_sound-alike_ only), and _obvious_ printer errors. But we don't re-edit the book or apply our preferences (believe me, I would like to; apparently they got paid by the comma in the 1700's). Several of the "printer error" commits thus are not printer errors.

In general, "missing" dashes aren't printer errors. They didn't dash the word either because it wasn't dashed at the time, or the editor didn't want it dashed, etc., etc. As with the comment on the other issue, we generally don't mess with words that modernize spelling doesn't handle, but we _definitely_ don't make changes that aren't supported by M-W.

Punctuation different than what we might use is also not a printer error. It's a difference of editorial opinion, and the actual (professional) editor of the book gets preference over us producers. :)

Obvious missing punctuation (emphasis on the "obvious"), e.g. missing periods at the end of a sentence, or a missing opening/closing quote on dialog, etc., are almost certainly printer errors and can be fixed as such.

These commits are not printer errors, and so should be dropped.
- [x] 4489818; that phrasing is quite common.
- [x] 4f2c26b; the comma after "whatever" is probably OK, but the "give" is almost certainly vernacular as Jack spoke it, and should be left.
- [x] 64e4dfe; see above
- [x] 2f2f706; only 2 is likely, and even it could be intentional. Interne is a valid variant for interne, and "next me" is again quite common phrasing.
- [x] 3964e28; again, common phrasing.
- [x] 2814fb05; the missing period on "toes" is correct; the other is not. What sound like questions don't always end in question marks; sometimes they end in periods, in exclamation marks, etc. Again, quite common.
- [x] 554547c; he's stating the truth, so he begins the truth he's stating with a capital letter. That is valid. (And not just for the time; that can be seen even in books today.)
- [x] 535989c; same as 2f2f706.
- [x] 96a2853; same as 64e4dfe.
- [x] c78b0b6; ditto.
- [x] 06138c0; see above
- [x] d10720c; see above
- [x] 13fa92c; see above
- [x] 7a967f0; see above
- [x] 9f8327d; I can easily see Jack using "escapes" (and can imagine that it was even vernacular), and, as elsewhere, not having a dash isn't a printer error, and hop-fiend isn't in M-W.

**Comment by jlund** [comment]
These are in progress. I'm going to mark them as complete as I fix them in my local branch. I'll comment here again when everything has been pushed.

**Comment by jlund** [comment]
Thanks. These are really good suggestions. I have all of these cleaned up now, and the changes have been pushed to the main branch.

> https://github.com/jlund/jack-black_you-cant-win/commit/4489818b88f2c57a6551126acd41ae73cb023ba0; that phrasing is quite common.

I feel a bit silly that I hadn't heard this before. I was listening to a podcast a couple of weeks ago and the host said "in future" several times, which made me realize that these changes were a mistake. I had reverted them [here](https://github.com/jlund/jack-black_you-cant-win/commit/9af6b088b652771797e785243fba03168a9f2c2a), but now I have also dropped all of the related "in (the) future" commits for a cleaner and less confusing history too.

> https://github.com/jlund/jack-black_you-cant-win/commit/4f2c26be523416ba724bcff0cefb19d6be24cbfd; the comma after "whatever" is probably OK, but the "give" is almost certainly vernacular as Jack spoke it, and should be left.

Good call. I edited this commit and commit message to drop the give/gave change, but I kept the comma removal intact. That one still feels like it was most likely an error.

> https://github.com/jlund/jack-black_you-cant-win/commit/2f2f706b6cbed8df950d8da9cbc9de61abf0a29b; only 2 is likely, and even it could be intentional. Interne is a valid variant for interne, and "next me" is again quite common phrasing.

Fully dropped. With the benefit of hindsight, I agree with you that "many thinks" could be an intentional choice to reflect Julia's accent. Better to err on the side of restraint.

> https://github.com/jlund/jack-black_you-cant-win/commit/2814fb0586c155811c0fa2471b3314b8d42b3e68; the missing period on "toes" is correct; the other is not. What sound like questions don't always end in question marks; sometimes they end in periods, in exclamation marks, etc. Again, quite common.

I edited this commit and only kept the missing period after "toes."

> https://github.com/jlund/jack-black_you-cant-win/commit/64e4dfe5fbb3acf7b1a08e75928ce3f908f304c0; see above
> https://github.com/jlund/jack-black_you-cant-win/commit/3964e28a611ecd9fef386524ee821974a8f91c48; again, common phrasing.
> https://github.com/jlund/jack-black_you-cant-win/commit/554547c1e5d3a2a6a57f6da849f5d799c2862f13; he's stating the truth, so he begins the truth he's stating with a capital letter. That is valid. (And not just for the time; that can be seen even in books today.)
> https://github.com/jlund/jack-black_you-cant-win/commit/535989cb2736178ce4af22f1a23ee1807b31e184; same as https://github.com/jlund/jack-black_you-cant-win/commit/2f2f706b6cbed8df950d8da9cbc9de61abf0a29b.
> https://github.com/jlund/jack-black_you-cant-win/commit/96a2853e91d6f2a6ac8f8abb48689f4a4a00cf74; same as https://github.com/jlund/jack-black_you-cant-win/commit/64e4dfe5fbb3acf7b1a08e75928ce3f908f304c0.
> https://github.com/jlund/jack-black_you-cant-win/commit/c78b0b6d9fdd68b709dc3464fa634569fafa12c1; ditto.
> https://github.com/jlund/jack-black_you-cant-win/commit/06138c00138a6ea8bf9e7b321c1892110829d50b; see above
> https://github.com/jlund/jack-black_you-cant-win/commit/d10720cd7fae41ee25655795a117ee6e1ea6f58d; see above
> https://github.com/jlund/jack-black_you-cant-win/commit/13fa92cf73adc2820fe11726c707bea7e7877149; see above
> https://github.com/jlund/jack-black_you-cant-win/commit/7a967f00296446cd7baa70c7e098c3700962af59; see above
> https://github.com/jlund/jack-black_you-cant-win/commit/9f8327d65780bf24be19cca1865f63ccb4c6e12c; I can easily see Jack using "escapes" (and can imagine that it was even vernacular), and, as elsewhere, not having a dash isn't a printer error, and hop-fiend isn't in M-W.

All of these commits have been dropped.

I'm going to address the last two things that were mentioned in the email thread now. I'll post an update there when the repo is ready for another look.

Thanks again!
