### ISSUE TITLE
Transcriber

### ISSUE THREAD

**Issue by vr8hub** [jlund/jack-black_you-cant-win#4]
Sorry I've been silent the last couple of days, when you're a volunteer sometimes real life takes precedence. :)

I've done some research in the corpus on transcriptions done by the producer when the transcription isn't publicly available, e.g. on PG; especially on Alex's, as he's done a few, and I believe this is what it should look like.
- [X] The metadata (content.opf) should have no transcriber-1, and there should be a "trc" role underneath producer-1. You have this, so this is good.
- [x] Colophon should not mention transcriber/transcriptions, either. So, instead of `is based on a transcription… and on digital scans…` it should just say `is based on digital scans…`. So just as you're not mentioned as a transcriber in the metadata, you shouldn't be mentioned here, either.
- [X] Same for imprint, no mention of transcriptions at all. Like the metadata, your imprint looks good.

So, I believe just fixup the colophon and we're good. Run lint a final time after the change just to make sure.

**Comment by jlund** [comment]
No need to apologize! I'm sorry if my enthusiasm ever came across as impatience :)

Thanks for figuring out the right way to do this. I updated the colophon as you suggested. I really appreciate all of your help getting this ready to release. Your thoughtful and positive feedback has really meant a lot to me.
